export class GetAFriend {
  constructor (
  /** note holds text to be printed on card **/
  public note:string,
  /** length of note. Used when creating output to determine CSS class **/
  public noteLength:number,
  /** order number generated by platform in the format #nnnnnnnn... **/
  public platformOrderNumber:string,
  /** If any error set to true with description message **/
  public error:boolean,
  public errorTxt:string|null) {}
}
